name: "Release to Steam"
author: chtzvt
description: Releases a multi-platform game on Steam
branding:
  icon: 'send'  
  color: 'gray-dark'

inputs:
  steam-totp-shared-secret: 
    description: "Your Steam TOTP shared secret"
    required: true
  steam-username:
    description: "Your Steam username"
    required: true 
  steam-password: 
    description: "Your Steam API key"
    required: true 
  steam-appid: 
    description: "Published version, typically a release tag name"
    required: true 
  version: 
    description: "Published version description, typically a release tag name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install libcurl 
      shell: bash
      id: libcurl_install
      run: |
        sudo apt -y install libcurl4-openssl-dev libnss-wrapper libcurl4
    - name: Download Game Build Artifacts
      uses: actions/download-artifact@v3.0.2
      with:
        path: builds/
    - name: "Unpack artifacts for publishing"
      shell: bash
      run: |
          mkdir -p builds/StandaloneWindows64
          mkdir -p builds/StandaloneLinux64
          mkdir -p builds/StandaloneOSX

          cp 'builds/build-Windows/Windows.zip' .
          unzip Windows.zip -d builds/StandaloneWindows64

          cp 'builds/build-Linux_X11/Linux_X11.zip' .
          unzip Linux_X11.zip -d builds/StandaloneLinux64

          cp 'builds/build-macOS/macOS.zip' .
          unzip macOS.zip -d builds/StandaloneOSX
    - uses: The-Water-Museum/steam-totp@v1.0.3
      name: Generate TOTP
      id: steam-totp
      with:
        shared_secret: ${{ inputs.steam-totp-shared-secret }}
    - uses: The-Water-Museum/steam-deploy@v1.3.0
      with:
        username: ${{ inputs.steam-username }}
        password: ${{ inputs.steam-password }}
        totp: ${{ steps.steam-totp.outputs.code }}
        appId: ${{ inputs.steam-appid }} 
        buildDescription: ${{ inputs.version }}
        rootPath: builds
        depot1Path: StandaloneWindows64
        depot2Path: StandaloneOSX
        depot3Path: StandaloneLinux64
        releaseBranch: prerelease
